# This is an EDA (Exploratory Data Analysis) Script for Behaviour Logging of HiFPT Apps. The purpose is to observe the features, take some statistical number from the data.

In [53]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data_path = "../data/HiFPT_july_events.csv"
df = pd.read_csv(data_path, delimiter = ",")

C:\Users\HP\AppData\Local\Temp\ipykernel_4720\193951839.py:6: DtypeWarning: Columns (0: segmentation.platform, 1: segmentation.stable) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(data_path, delimiter = ",")

In [2]:
dropped_columns = ["id_data.vid", "process", "campaign_ids", "utm_source", 'ip_address', "segmentation.data.order_id",  "segmentation.data.transaction_id", "segmentation.data.status", "segmentation.session_id", "segmentation.data.report_id", "segmentation.stable", "segmentation.platform"]

In [61]:
dropped_columns = ["campaign_ids", "app_id", ]

In [62]:
df.drop(columns = dropped_columns, inplace = True)

## 1. Data Inspection

### 1a. Data records:

In [60]:
df.head()

,record_id,device_id,customer_id,session_id,created_at,timestamp,key,segmentation.name,segmentation.segment,duration,segmentation.start,segmentation.screen_id
0,6a62c659b83c7ae211d5ebf7,9A33E8AB-A255-4767-AB89-DCBF4ABB532D,7345324.0,54A4F343-C142-48A6-AF20-A357C6CAB802,2026-07-24T01:56:41.530Z,1782890381445,View,SplashVC,iOS,1,NaN,NaN
1,6a62c659b83c7ae211d5ebf5,9A33E8AB-A255-4767-AB89-DCBF4ABB532D,7345324.0,54A4F343-C142-48A6-AF20-A357C6CAB802,2026-07-24T01:56:41.530Z,1782890379982,View,SplashVC,iOS,0,1.0,NaN
2,6a62c6592145c174196114aa,9A33E8AB-A255-4767-AB89-DCBF4ABB532D,7345324.0,54A4F343-C142-48A6-AF20-A357C6CAB802,2026-07-24T01:56:41.473Z,1782890381462,View,SplashVC,iOS,1,NaN,NaN
3,6a5e1404a985eb775e731be0,790D2635-B076-43F8-87DB-B4095CE95FE3,2004212.0,B03F54FE-68F3-4311-BD24-F5BC0244CB83,2026-07-20T12:26:44.082Z,1783428581782,View,https://staging-hi.fpt.vn/dkol/update-package/...,iOS,13986,NaN,NaN
4,6a5e1403da79ea6ce327260e,790D2635-B076-43F8-87DB-B4095CE95FE3,2004212.0,B03F54FE-68F3-4311-BD24-F5BC0244CB83,2026-07-20T12:26:43.262Z,1783428581780,View,WebkitEcommerceController,iOS,13986,NaN,NaN

In [17]:
df.tail(10)

,_id.$oid,device_id,customer_id,session_id,created_at.$date,timestamp,key,segmentation.name,segmentation.segment,dur,segmentation.visit,segmentation.start,segmentation.screen_id,segmentation.external_id,segmentation.$stable,segmentation.class_name,segmentation.platform,segmentation.stable
122120,6a68310cd29b498240b19dc7,F4E2DE3A-E261-4DF4-BC01-C312BC2B9FA9,6788406.0,B8171F96-1D5F-4921-9660-CE9AD80317E8,2026-07-28T04:33:16.572Z,1785213196257,[CLY]_view,PopupWithCustomContentVC,iOS,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122121,6a68310cd29b498240b19dc6,F4E2DE3A-E261-4DF4-BC01-C312BC2B9FA9,6788406.0,B8171F96-1D5F-4921-9660-CE9AD80317E8,2026-07-28T04:33:16.572Z,1785213193095,[CLY]_view,PopupWithCustomContentVC,iOS,0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122122,6a68310cd29b498240b19dc5,F4E2DE3A-E261-4DF4-BC01-C312BC2B9FA9,6788406.0,B8171F96-1D5F-4921-9660-CE9AD80317E8,2026-07-28T04:33:16.572Z,1785213193086,[CLY]_view,UIViewController,iOS,0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122123,6a68310b91d5775df67fc4bd,939335e13de914bf,NaN,7cdcedd0-49be-4d31-8b1b-be39ae19ae08,2026-07-28T04:33:15.588Z,1785213194431,[CLY]_view,NotificationDetailActivity,Android,0,1.0,NaN,NaN,NaN,8.0,NotificationDetailActivity,NaN,NaN
122124,6a68310b91d5775df67fc4bc,939335e13de914bf,NaN,7cdcedd0-49be-4d31-8b1b-be39ae19ae08,2026-07-28T04:33:15.584Z,1785213194430,[CLY]_view,home_guest,Android,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122125,6a68310b31f381b085096977,939335e13de914bf,NaN,7cdcedd0-49be-4d31-8b1b-be39ae19ae08,2026-07-28T04:33:15.562Z,1785213194559,[CLY]_view,android/NOTIFICATION/DETAIL,Android,0,1.0,NaN,NaN,NaN,8.0,android/NOTIFICATION/DETAIL,NaN,NaN
122126,6a68310b31f381b085096976,939335e13de914bf,NaN,7cdcedd0-49be-4d31-8b1b-be39ae19ae08,2026-07-28T04:33:15.560Z,1785213194558,[CLY]_view,NotificationDetailActivity,Android,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122127,6a68310b4309b28aae6b9b64,939335e13de914bf,NaN,7cdcedd0-49be-4d31-8b1b-be39ae19ae08,2026-07-28T04:33:15.194Z,1785213194247,[CLY]_view,HOME,Android,0,1.0,NaN,NaN,NaN,8.0,HOME,NaN,NaN
122128,6a68310b4309b28aae6b9b63,939335e13de914bf,NaN,7cdcedd0-49be-4d31-8b1b-be39ae19ae08,2026-07-28T04:33:15.193Z,1785213194246,[CLY]_view,Splash,Android,1,NaN,NaN,NaN,NaN,8.0,Splash,NaN,NaN
122129,6a68310b5bc9ca8fa0dc241d,939335e13de914bf,NaN,7cdcedd0-49be-4d31-8b1b-be39ae19ae08,2026-07-28T04:33:15.193Z,1785213193755,[CLY]_view,Splash,Android,0,1.0,1.0,NaN,NaN,8.0,Splash,NaN,NaN

In [18]:
df.shape #shape í s a tuple of (#rows, #cols).
#df.size is number of total element records -> Rows x Cols.
#df.ndim -> Dimension of data. Table data is 2D.

(122130, 18)

### 1b. Data Overall Summary: 
- Statistics: including count, mean, std, min, interquantile range and maximum value. 
- info like non-null counts, dtypes of columns.

In [19]:
df.describe()

,customer_id,timestamp,dur,segmentation.visit,segmentation.start,segmentation.$stable
count,1.029960e+05,1.221300e+05,122130.000000,45966.0,4076.0,24094.0
mean,4.775464e+06,1.784310e+12,24.368812,1.0,1.0,8.0
std,2.581131e+06,7.186121e+08,914.517200,0.0,0.0,0.0
min,1.990000e+02,1.782840e+12,0.000000,1.0,1.0,8.0
25%,2.004212e+06,1.783416e+12,0.000000,1.0,1.0,8.0
50%,6.788406e+06,1.784532e+12,0.000000,1.0,1.0,8.0
75%,6.793513e+06,1.784629e+12,2.000000,1.0,1.0,8.0
max,7.345726e+06,1.785381e+12,151728.000000,1.0,1.0,8.0

In [20]:
df.nunique() # This is for determine if a variable is continuous or discrete and its number of available values

_id.$oid                    122130
device_id                      196
customer_id                    133
session_id                    1581
created_at.$date             83174
timestamp                   121389
key                              2
segmentation.name             1841
segmentation.segment             2
dur                            776
segmentation.visit               1
segmentation.start               1
segmentation.screen_id         616
segmentation.external_id       219
segmentation.$stable             1
segmentation.class_name        113
segmentation.platform            2
segmentation.stable              1
dtype: int64

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 153068 entries, 0 to 153067
Data columns (total 18 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   _id.$oid                  153068 non-null  str
 1   device_id                 153068 non-null  str
 2   customer_id               132631 non-null  float64
 3   session_id                153068 non-null  str
 4   created_at.$date          153068 non-null  str
 5   timestamp                 153068 non-null  int64
 6   key                       153068 non-null  str
 7   segmentation.$stable      37009 non-null   float64
 8   segmentation.segment      153068 non-null  str
 9   segmentation.name         153045 non-null  str
 10  segmentation.visit        57931 non-null   float64
 11  segmentation.class_name   21460 non-null   str
 12  dur                       153068 non-null  int64
 13  segmentation.start        5454 non-null    float64
 14  segmentation.screen_id    35227 non-null   str
 15  segmentation.external_id  5632 non-null    str
 16  segmentation.stable       4 non-null       str
 17  segmentation.platform     9 non-null       str
dtypes: float64(4), int64(2), str(12)
memory usage: 21.0 MB

In [21]:
df.sort_values(by = "created_at.$date", ascending = True)

,_id.$oid,device_id,customer_id,session_id,created_at.$date,timestamp,key,segmentation.name,segmentation.segment,dur,segmentation.visit,segmentation.start,segmentation.screen_id,segmentation.external_id,segmentation.$stable,segmentation.class_name,segmentation.platform,segmentation.stable
33284,6a4b25d09cda512d21494630,1a5bebf736eb9d7a,2004381.0,5a143dd0-4a96-41bd-a5de-bc0c845ffb32,2026-07-06T03:49:36.325Z,1783309776293,[CLY]_view,SplashActivity,Android,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33283,6a4b25d09cda512d2149462f,1a5bebf736eb9d7a,2004381.0,5a143dd0-4a96-41bd-a5de-bc0c845ffb32,2026-07-06T03:49:36.326Z,1783309776147,[CLY]_view,SplashActivity,Android,0,1.0,NaN,NaN,NaN,8.0,SplashActivity,NaN,NaN
33282,6a4b25d09cda512d21494631,1a5bebf736eb9d7a,2004381.0,5a143dd0-4a96-41bd-a5de-bc0c845ffb32,2026-07-06T03:49:36.328Z,1783309776303,[CLY]_view,MainAppActivity,Android,0,1.0,NaN,NaN,NaN,8.0,MainAppActivity,NaN,NaN
33281,6a4b25d10713cb0ae5d8f880,1a5bebf736eb9d7a,2004381.0,5a143dd0-4a96-41bd-a5de-bc0c845ffb32,2026-07-06T03:49:37.334Z,1783309777375,[CLY]_view,MainAppActivity,Android,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33280,6a4b25d25f185618f1c70b01,1a5bebf736eb9d7a,2004381.0,5a143dd0-4a96-41bd-a5de-bc0c845ffb32,2026-07-06T03:49:38.328Z,1783309777379,[CLY]_view,Splash,Android,0,1.0,1.0,NaN,NaN,8.0,Splash,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92357,6a6abfba4309b28aae6bd8d3,4A7DC769-5C13-4A85-9AF5-C5A1833951FB,2003483.0,2EECE53F-8A14-4F8A-8699-4FA35CA8DBDB,2026-07-30T03:06:34.861Z,1785378748897,[CLY]_view,WebkitEcommerceController,iOS,47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92356,6a6abfba4309b28aae6bd8d4,4A7DC769-5C13-4A85-9AF5-C5A1833951FB,2003483.0,2EECE53F-8A14-4F8A-8699-4FA35CA8DBDB,2026-07-30T03:06:34.861Z,1785378748898,[CLY]_view,STWebRemoteViewController,iOS,47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92355,6a6abfbb91d5775df6800272,4A7DC769-5C13-4A85-9AF5-C5A1833951FB,2003483.0,2EECE53F-8A14-4F8A-8699-4FA35CA8DBDB,2026-07-30T03:06:35.078Z,1785378748877,[CLY]_view,WebkitEcommerceController,iOS,47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92354,6a6abfbb91d5775df6800273,4A7DC769-5C13-4A85-9AF5-C5A1833951FB,2003483.0,2EECE53F-8A14-4F8A-8699-4FA35CA8DBDB,2026-07-30T03:06:35.078Z,1785378748878,[CLY]_view,STWebRemoteViewController,iOS,46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92353,6a6abfbb91d5775df6800271,4A7DC769-5C13-4A85-9AF5-C5A1833951FB,2003483.0,2EECE53F-8A14-4F8A-8699-4FA35CA8DBDB,2026-07-30T03:06:35.082Z,1785378748876,[CLY]_view,BaseNavigation,iOS,85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### 1.c Data mising data info, count values and columns

In [22]:
na_series = df.isna().sum() #df.isna() returns pd.DataFrame: boolean matrix of original dataframe that the value is null will be N.A.
na_series[na_series > 0]

customer_id                  19134
segmentation.name                5
segmentation.visit           76164
segmentation.start          118054
segmentation.screen_id       93634
segmentation.external_id    118391
segmentation.$stable         98036
segmentation.class_name     107839
segmentation.platform       122127
segmentation.stable         122129
dtype: int64

In [23]:
df.columns

Index(['_id.$oid', 'device_id', 'customer_id', 'session_id',
       'created_at.$date', 'timestamp', 'key', 'segmentation.name',
       'segmentation.segment', 'dur', 'segmentation.visit',
       'segmentation.start', 'segmentation.screen_id',
       'segmentation.external_id', 'segmentation.$stable',
       'segmentation.class_name', 'segmentation.platform',
       'segmentation.stable'],
      dtype='str')

In [24]:
df.nunique() # Count distinct value in each column of a dataframe.

_id.$oid                    122130
device_id                      196
customer_id                    133
session_id                    1581
created_at.$date             83174
timestamp                   121389
key                              2
segmentation.name             1841
segmentation.segment             2
dur                            776
segmentation.visit               1
segmentation.start               1
segmentation.screen_id         616
segmentation.external_id       219
segmentation.$stable             1
segmentation.class_name        113
segmentation.platform            2
segmentation.stable              1
dtype: int64

In [25]:
df["key"].value_counts() # -> Return value counts for each value in column.

key
[CLY]_view    93100
action        29030
Name: count, dtype: int64

In [27]:
df["segmentation.name"].value_counts()

segmentation.name
MainTabBarController                                7571
HomeVC                                              6033
WebkitEcommerceController                           5563
BaseNavigation                                      4006
UIViewController                                    3033
                                                    ...
CAMViewfinderViewController                            1
CAMImagePickerCameraViewController                     1
PUPhotoPickerHostViewController                        1
sign_econtract_success/click_close                     1
guest/Transaction_result/icon buttons/Click_home       1
Name: count, Length: 1841, dtype: int64

In [28]:
df["segmentation.screen_id"].value_counts()

segmentation.screen_id
HomeVC                                                                                                    2980
LoginVC                                                                                                   1191
PaymentInfoScreenData                                                                                     1166
ServiceManageVC                                                                                           1063
ChooseContractVC                                                                                          1015
                                                                                                          ...
QuoteAndMinutesEcontractVC                                                                                   1
https://staging-hi.fpt.vn/web/survey/csat/view-rating?surveyId=18846&contractNo=SGABN6831&is_from=noti       1
android/Home/payment_extend_detail                                                                           1
android/login_screen/OTP_screen                                                                              1
ProfileInformationVC                                                                                         1
Name: count, Length: 616, dtype: int64

In [29]:
session_counts = df["session_id"].value_counts()
print(session_counts.index)

Index(['22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9',
       'A76EDC8D-DE15-4A59-870E-25E6CF71315F',
       'e7b190d5-9dce-4f30-922b-cf2b5063079e',
       '8FBC36E5-95FF-4E18-AE44-E82B0558EAF7',
       '3341F3CA-C1C1-442E-B69A-72EDBEB351FF',
       'DDC0AFD3-C2D2-4E53-A9A7-F92179A327E7',
       '7DD52A31-8C5B-4B8E-8DBE-BCDBF99AC809',
       '40543C41-9E82-4C50-A8C2-7B717995E8FA',
       'FBF5A138-A917-4A38-BFE8-51060D5AA7B6',
       'E4D1B9D4-4940-4E3F-AAD9-20FF93A44B32',
       ...
       'e381b6a9-67a2-4740-aa6f-63d0a39f35c4',
       '418eaaf3-4e4a-4f9d-861d-877d617cc2d2',
       '4cb5f77a-1038-411c-af37-2e69cffb10e7',
       '8e660799-929f-4251-90ba-55221d2c4518',
       '151d29b6-1b5b-4029-90a3-0a6eacf3b2c8',
       '0c9455a9-ad7f-426f-97fb-51679693f153',
       '39c87830-50fd-4f49-8d35-a76397cce708',
       '77e21e8b-6ce6-426f-abd5-c6aacfc5b1b7',
       '8ba279e1-8fc6-41f9-9869-85828c815553',
       'f799b8b9-467c-49ab-802f-9e0e0b90781b'],
      dtype='str', name='session_id', length=1581)

In [30]:
sample_session = (
    df[df["session_id"] == df["session_id"].value_counts().index[0]] #Index is used to label and identify each element of the data -> In this case: the label for each value is the count of each session. Index[0] is the first session_id.
    .sort_values("timestamp")
)

print(f"Len of sample session {session_counts.index[0]} : {len(sample_session)}")

sample_session[
    [
        "session_id",
        "timestamp",
        "key",
        "segmentation.name",
        "segmentation.screen_id",
        "dur",
    ]
].head(50)

Len of sample session 22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9 : 3456

,session_id,timestamp,key,segmentation.name,segmentation.screen_id,dur
56429,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783993981069,[CLY]_view,SplashVC,NaN,0
56428,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783993984465,[CLY]_view,SplashVC,NaN,3
56427,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783993984495,[CLY]_view,MainTabBarController,NaN,0
56426,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783993984498,[CLY]_view,HomeVC,NaN,0
56424,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783993984980,action,show/popup/remind_noti,HomeVC,0
56425,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783993984986,[CLY]_view,PopupVC,NaN,0
56422,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783993987547,[CLY]_view,PopupVC,NaN,3
56423,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783993987553,action,home/popup_remind/skip_remind,HomeVC,0
56418,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783993988441,action,Home/change_contract,HomeVC,0
56419,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783993988472,[CLY]_view,ChooseContractVC,NaN,0
56420,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783993988477,[CLY]_view,MainTabBarController,NaN,4
56421,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783993988479,[CLY]_view,HomeVC,NaN,4
56417,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783993989712,action,btn_link_contract,ChooseContractVC,0
56416,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783993989726,[CLY]_view,LinkContractVC,NaN,0
56415,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783993989728,[CLY]_view,ChooseContractVC,NaN,1
56414,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783993992308,action,btn_back,LinkContractVC,0
56412,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783993992323,[CLY]_view,ChooseContractVC,NaN,0
56413,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783993992334,[CLY]_view,LinkContractVC,NaN,3
56410,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783993993054,action,btn_back,ChooseContractVC,0
56411,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783993993074,[CLY]_view,MainTabBarController,NaN,0
56409,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783993993077,[CLY]_view,HomeVC,NaN,0
56406,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783993993104,[CLY]_view,ChooseContractVC,NaN,1
56408,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783993994209,action,Home/other_manage_internet,HomeVC,0
56407,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783993994223,[CLY]_view,ServiceManageVC,NaN,0
56405,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783993994230,[CLY]_view,MainTabBarController,NaN,1
56404,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783993994231,[CLY]_view,HomeVC,NaN,1
56403,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783994000929,action,home/home_service_management/internet_service_...,ServiceManageVC,0
56402,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783994001788,[CLY]_view,WebkitEcommerceController,NaN,0
56401,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783994001797,[CLY]_view,ServiceManageVC,NaN,8
56399,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783994002629,[CLY]_view,https://staging-hi.fpt.vn/dkol/update-package/...,NaN,0
56400,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783994003082,action,webUpdatePackage_Home,https://staging-hi.fpt.vn/dkol/update-package/...,0
56398,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783994004429,action,webUpdatePackage_Home_CheckContract,https://staging-hi.fpt.vn/dkol/update-package/...,0
56397,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783994004434,action,webUpdatePackage_Home_getListServiceSaleType,https://staging-hi.fpt.vn/dkol/update-package/...,0
56396,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783994004621,action,webUpdatePackage_Home_getListServiceSaleType,https://staging-hi.fpt.vn/dkol/update-package/...,0
56395,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783994032765,[CLY]_view,UIViewController,NaN,0
56394,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783994032778,[CLY]_view,PopupWithCustomContentVC,NaN,0
56388,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783994046175,[CLY]_view,PopupWithCustomContentVC,NaN,13
56386,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783994046178,[CLY]_view,UIViewController,NaN,13
56387,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783994047694,[CLY]_view,UIViewController,NaN,0
56385,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783994047703,[CLY]_view,PopupWithCustomContentVC,NaN,0
56384,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783994048972,[CLY]_view,PopupWithCustomContentVC,NaN,1
56383,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783994048978,[CLY]_view,UIViewController,NaN,1
56377,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783994055709,[CLY]_view,https://staging-hi.fpt.vn/dkol/update-package/...,NaN,53
56376,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783994055710,[CLY]_view,WebkitEcommerceController,NaN,54
56231,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783994419593,[CLY]_view,https://staging-hi.fpt.vn/dkol/update-package/...,NaN,0
56232,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783994419596,[CLY]_view,WebkitEcommerceController,NaN,0
56225,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783994450265,[CLY]_view,https://staging-hi.fpt.vn/dkol/update-package/...,NaN,31
56224,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783994450266,[CLY]_view,WebkitEcommerceController,NaN,31
56223,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783994452061,[CLY]_view,https://staging-hi.fpt.vn/dkol/update-package/...,NaN,0
56222,22724B6D-EBBC-43D3-A5E1-B1A6E2687ED9,1783994452064,[CLY]_view,WebkitEcommerceController,NaN,0

In [31]:
summary = pd.DataFrame({
    "dtype": df.dtypes.astype(str),
    "non_null": df.notna().sum(),
    "missing": df.isna().sum(),
    "missing_pct": df.isna().mean().mul(100),
    "n_unique": df.nunique(dropna=True)
})

summary["unique_pct"] = (
    summary["n_unique"] / len(df) * 100
)

summary.sort_values("missing_pct", ascending=False)

,dtype,non_null,missing,missing_pct,n_unique,unique_pct
segmentation.stable,str,1,122129,99.999181,1,0.000819
segmentation.platform,str,3,122127,99.997544,2,0.001638
segmentation.external_id,str,3739,118391,96.938508,219,0.179317
segmentation.start,float64,4076,118054,96.662573,1,0.000819
segmentation.class_name,str,14291,107839,88.298534,113,0.092524
segmentation.$stable,float64,24094,98036,80.271841,1,0.000819
segmentation.screen_id,str,28496,93634,76.667485,616,0.504381
segmentation.visit,float64,45966,76164,62.363056,1,0.000819
customer_id,float64,102996,19134,15.666912,133,0.108900
segmentation.name,str,122125,5,0.004094,1841,1.507410
device_id,str,122130,0,0.000000,196,0.160485
_id.$oid,str,122130,0,0.000000,122130,100.000000
dur,int64,122130,0,0.000000,776,0.635389
segmentation.segment,str,122130,0,0.000000,2,0.001638
session_id,str,122130,0,0.000000,1581,1.294522
created_at.$date,str,122130,0,0.000000,83174,68.102841
key,str,122130,0,0.000000,2,0.001638
timestamp,int64,122130,0,0.000000,121389,99.393269

In [54]:
df.rename(
    columns = {
        "_id.$oid": "record_id",
        "created_at.$date": "created_at",
        "dur": "duration"
    }, inplace = True
)

# 2. Rename columns

In [58]:
df.columns

Index(['record_id', 'device_id', 'customer_id', 'session_id', 'created_at',
       'timestamp', 'key', 'segmentation.name', 'segmentation.segment',
       'duration', 'segmentation.start', 'segmentation.screen_id'],
      dtype='str')

In [56]:
df.drop(columns = ["segmentation.class_name", 'segmentation.external_id', 'segmentation.$stable', "segmentation.visit", "segmentation.stable", "segmentation.platform"], inplace = True)

In [57]:
df["key"] = df["key"].map(
{
    "[CLY]_view": "View",
    "action": "Action"
}
) # Return series.

In [59]:
df.to_csv("../data/clean_july_events.csv", index = False)

In [23]:
df_check = df.loc[:, ["activity", "segmentation.class_name"]]
df_check.dropna(how = "any", axis = 0, inplace = True)

In [ ]:
df_check_boolean = df_check.mask(df_check["activity"] == df_check["segmentation.class_name"], 1) # Condition if not 
df.where()
df.loc[df_check_boolean.index.to_list(), ["activity", "segmentation.class_name"]]

                           activity      segmentation.class_name
5                    SplashActivity               SplashActivity
7                   MainAppActivity              MainAppActivity
11                           Splash                       Splash
14                             HOME                         HOME
16                     android/Home                 android/Home
...                             ...                          ...
246759                       Splash                       Splash
246772                         HOME                         HOME
246785                 android/Home                 android/Home
246810                 android/Home                 android/Home
246811  android/home/support_create  android/home/support_create

[16912 rows x 2 columns]

In [34]:
print(len(df_check_boolean))
len(df_check_boolean[df[["activity", "segmentation.class_name"]] == 1])

16912

16912

# 3. Separate into Android and IOS data

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data_path = "../data/clean_july_events.csv"
df = pd.read_csv(data_path, delimiter = ",")

In [3]:
df

,record_id,device_id,customer_id,session_id,created_at,timestamp,key,segmentation.name,segmentation.segment,duration,segmentation.start,segmentation.screen_id
0,6a62c659b83c7ae211d5ebf7,9A33E8AB-A255-4767-AB89-DCBF4ABB532D,7345324.0,54A4F343-C142-48A6-AF20-A357C6CAB802,2026-07-24T01:56:41.530Z,1782890381445,View,SplashVC,iOS,1,NaN,NaN
1,6a62c659b83c7ae211d5ebf5,9A33E8AB-A255-4767-AB89-DCBF4ABB532D,7345324.0,54A4F343-C142-48A6-AF20-A357C6CAB802,2026-07-24T01:56:41.530Z,1782890379982,View,SplashVC,iOS,0,1.0,NaN
2,6a62c6592145c174196114aa,9A33E8AB-A255-4767-AB89-DCBF4ABB532D,7345324.0,54A4F343-C142-48A6-AF20-A357C6CAB802,2026-07-24T01:56:41.473Z,1782890381462,View,SplashVC,iOS,1,NaN,NaN
3,6a5e1404a985eb775e731be0,790D2635-B076-43F8-87DB-B4095CE95FE3,2004212.0,B03F54FE-68F3-4311-BD24-F5BC0244CB83,2026-07-20T12:26:44.082Z,1783428581782,View,https://staging-hi.fpt.vn/dkol/update-package/...,iOS,13986,NaN,NaN
4,6a5e1403da79ea6ce327260e,790D2635-B076-43F8-87DB-B4095CE95FE3,2004212.0,B03F54FE-68F3-4311-BD24-F5BC0244CB83,2026-07-20T12:26:43.262Z,1783428581780,View,WebkitEcommerceController,iOS,13986,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
122125,6a68310b31f381b085096977,939335e13de914bf,NaN,7cdcedd0-49be-4d31-8b1b-be39ae19ae08,2026-07-28T04:33:15.562Z,1785213194559,View,android/NOTIFICATION/DETAIL,Android,0,NaN,NaN
122126,6a68310b31f381b085096976,939335e13de914bf,NaN,7cdcedd0-49be-4d31-8b1b-be39ae19ae08,2026-07-28T04:33:15.560Z,1785213194558,View,NotificationDetailActivity,Android,0,NaN,NaN
122127,6a68310b4309b28aae6b9b64,939335e13de914bf,NaN,7cdcedd0-49be-4d31-8b1b-be39ae19ae08,2026-07-28T04:33:15.194Z,1785213194247,View,HOME,Android,0,NaN,NaN
122128,6a68310b4309b28aae6b9b63,939335e13de914bf,NaN,7cdcedd0-49be-4d31-8b1b-be39ae19ae08,2026-07-28T04:33:15.193Z,1785213194246,View,Splash,Android,1,NaN,NaN
122129,6a68310b5bc9ca8fa0dc241d,939335e13de914bf,NaN,7cdcedd0-49be-4d31-8b1b-be39ae19ae08,2026-07-28T04:33:15.193Z,1785213193755,View,Splash,Android,0,1.0,NaN

In [4]:
df_android = df[df["segmentation.segment"] == "Android"]
df_ios = df[df["segmentation.segment"] == "iOS"]

# Save into separate files
df_android.to_csv("../data/clean_july_events_android.csv", index = False)
df_ios.to_csv("../data/clean_july_events_ios.csv", index = False)